// <auto-generated />
#nullable enable
namespace InvoiceApp.Resources
{
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;

    [global::System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "8.0.0.0")]
    internal static class Strings
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (resourceMan == null)
                {
                    resourceMan = new ResourceManager("InvoiceApp.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                }
                return resourceMan;
            }
        }

        internal static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string ConfirmDeletionFormat => ResourceManager.GetString("ConfirmDeletionFormat", resourceCulture)!;
        internal static string ConfirmationTitle => ResourceManager.GetString("ConfirmationTitle", resourceCulture)!;
        internal static string ErrorTitle => ResourceManager.GetString("ErrorTitle", resourceCulture)!;
        internal static string DashboardLoadError => ResourceManager.GetString("DashboardLoadError", resourceCulture)!;
        internal static string PaymentMethodLoadError => ResourceManager.GetString("PaymentMethodLoadError", resourceCulture)!;
        internal static string ProductGroupLoadError => ResourceManager.GetString("ProductGroupLoadError", resourceCulture)!;
        internal static string TaxRateLoadError => ResourceManager.GetString("TaxRateLoadError", resourceCulture)!;
        internal static string UnitLoadError => ResourceManager.GetString("UnitLoadError", resourceCulture)!;
        internal static string ProductLoadError => ResourceManager.GetString("ProductLoadError", resourceCulture)!;
        internal static string SupplierLoadError => ResourceManager.GetString("SupplierLoadError", resourceCulture)!;
        internal static string InvoiceLoadError => ResourceManager.GetString("InvoiceLoadError", resourceCulture)!;
        internal static string UnexpectedErrorFormat => ResourceManager.GetString("UnexpectedErrorFormat", resourceCulture)!;
    }
}
#nullable restore
